//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiDataServicesParametersSample.BiDataServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingResponse", Namespace="http://schemas.datacontract.org/2004/07/UltimateSoftware.WcfTypes.Base")]
    public partial class PingResponse : object
    {
        
        private string AppDomainNameField;
        
        private string CallerIPAddressField;
        
        private BiDataServicesParametersSample.BiDataServices.PingResponse ChildField;
        
        private string ExceptionDetailsField;
        
        private string ExceptionMessageField;
        
        private BiDataServicesParametersSample.BiDataServices.NameValueCollection InformationField;
        
        private string ListenerUriField;
        
        private string MachineNameField;
        
        private string ProcessNameField;
        
        private string StackTraceField;
        
        private string TargetUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppDomainName
        {
            get
            {
                return this.AppDomainNameField;
            }
            set
            {
                this.AppDomainNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerIPAddress
        {
            get
            {
                return this.CallerIPAddressField;
            }
            set
            {
                this.CallerIPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiDataServicesParametersSample.BiDataServices.PingResponse Child
        {
            get
            {
                return this.ChildField;
            }
            set
            {
                this.ChildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionDetails
        {
            get
            {
                return this.ExceptionDetailsField;
            }
            set
            {
                this.ExceptionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage
        {
            get
            {
                return this.ExceptionMessageField;
            }
            set
            {
                this.ExceptionMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiDataServicesParametersSample.BiDataServices.NameValueCollection Information
        {
            get
            {
                return this.InformationField;
            }
            set
            {
                this.InformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListenerUri
        {
            get
            {
                return this.ListenerUriField;
            }
            set
            {
                this.ListenerUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName
        {
            get
            {
                return this.MachineNameField;
            }
            set
            {
                this.MachineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessName
        {
            get
            {
                return this.ProcessNameField;
            }
            set
            {
                this.ProcessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetUri
        {
            get
            {
                return this.TargetUriField;
            }
            set
            {
                this.TargetUriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameValueCollection", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Specialized")]
    public partial class NameValueCollection : BiDataServicesParametersSample.BiDataServices.NameObjectCollectionBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameObjectCollectionBase", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Specialized")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BiDataServicesParametersSample.BiDataServices.NameValueCollection))]
    public partial class NameObjectCollectionBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogOnRequest", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class LogOnRequest : object
    {
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string ClientAccessKeyField;
        
        private string UserAccessKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ClientAccessKey
        {
            get
            {
                return this.ClientAccessKeyField;
            }
            set
            {
                this.ClientAccessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string UserAccessKey
        {
            get
            {
                return this.UserAccessKeyField;
            }
            set
            {
                this.UserAccessKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataContext", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class DataContext : object
    {
        
        private string ServiceIdField;
        
        private string ClientAccessKeyField;
        
        private string TokenField;
        
        private BiDataServicesParametersSample.BiDataServices.ContextStatus StatusField;
        
        private string StatusMessageField;
        
        private string InstanceKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceId
        {
            get
            {
                return this.ServiceIdField;
            }
            set
            {
                this.ServiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ClientAccessKey
        {
            get
            {
                return this.ClientAccessKeyField;
            }
            set
            {
                this.ClientAccessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public BiDataServicesParametersSample.BiDataServices.ContextStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StatusMessage
        {
            get
            {
                return this.StatusMessageField;
            }
            set
            {
                this.StatusMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string InstanceKey
        {
            get
            {
                return this.InstanceKeyField;
            }
            set
            {
                this.InstanceKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContextStatus", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public enum ContextStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOff = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogOnWithTokenRequest", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class LogOnWithTokenRequest : object
    {
        
        private string TokenField;
        
        private string ClientAccessKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string ClientAccessKey
        {
            get
            {
                return this.ClientAccessKeyField;
            }
            set
            {
                this.ClientAccessKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportRequest", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class ReportRequest : object
    {
        
        private string ReportPathField;
        
        private BiDataServicesParametersSample.BiDataServices.ReportParameter[] ReportParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportPath
        {
            get
            {
                return this.ReportPathField;
            }
            set
            {
                this.ReportPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public BiDataServicesParametersSample.BiDataServices.ReportParameter[] ReportParameters
        {
            get
            {
                return this.ReportParametersField;
            }
            set
            {
                this.ReportParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportParameter", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class ReportParameter : object
    {
        
        private string NameField;
        
        private string ValueField;
        
        private bool RequiredField;
        
        private string DataTypeField;
        
        private bool MultiValuedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool Required
        {
            get
            {
                return this.RequiredField;
            }
            set
            {
                this.RequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DataType
        {
            get
            {
                return this.DataTypeField;
            }
            set
            {
                this.DataTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool MultiValued
        {
            get
            {
                return this.MultiValuedField;
            }
            set
            {
                this.MultiValuedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportResponse", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class ReportResponse : object
    {
        
        private string ReportKeyField;
        
        private System.Uri ReportRetrievalUriField;
        
        private BiDataServicesParametersSample.BiDataServices.ReportRequestStatus StatusField;
        
        private string StatusMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportKey
        {
            get
            {
                return this.ReportKeyField;
            }
            set
            {
                this.ReportKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ReportRetrievalUri
        {
            get
            {
                return this.ReportRetrievalUriField;
            }
            set
            {
                this.ReportRetrievalUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiDataServicesParametersSample.BiDataServices.ReportRequestStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage
        {
            get
            {
                return this.StatusMessageField;
            }
            set
            {
                this.StatusMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportRequestStatus", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public enum ReportRequestStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportListResponse", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class ReportListResponse : object
    {
        
        private BiDataServicesParametersSample.BiDataServices.Report[] ReportsField;
        
        private BiDataServicesParametersSample.BiDataServices.ReportRequestStatus StatusField;
        
        private string StatusMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BiDataServicesParametersSample.BiDataServices.Report[] Reports
        {
            get
            {
                return this.ReportsField;
            }
            set
            {
                this.ReportsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BiDataServicesParametersSample.BiDataServices.ReportRequestStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage
        {
            get
            {
                return this.StatusMessageField;
            }
            set
            {
                this.StatusMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class Report : object
    {
        
        private string ReportNameField;
        
        private string ReportPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportName
        {
            get
            {
                return this.ReportNameField;
            }
            set
            {
                this.ReportNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportPath
        {
            get
            {
                return this.ReportPathField;
            }
            set
            {
                this.ReportPathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportParameterResponse", Namespace="http://www.ultipro.com/dataservices/bidata/2")]
    public partial class ReportParameterResponse : object
    {
        
        private BiDataServicesParametersSample.BiDataServices.ReportParameter[] ReportParametersField;
        
        private BiDataServicesParametersSample.BiDataServices.ReportRequestStatus StatusField;
        
        private string StatusMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BiDataServicesParametersSample.BiDataServices.ReportParameter[] ReportParameters
        {
            get
            {
                return this.ReportParametersField;
            }
            set
            {
                this.ReportParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BiDataServicesParametersSample.BiDataServices.ReportRequestStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage
        {
            get
            {
                return this.StatusMessageField;
            }
            set
            {
                this.StatusMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ultipro.com/dataservices/bidata/2", ConfigurationName="BiDataServicesParametersSample.BiDataServices.IBIDataService")]
    public interface IBIDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUesWcfService/Ping", ReplyAction="http://tempuri.org/IUesWcfService/PingResponse")]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.PingResponse1> PingAsync(BiDataServicesParametersSample.BiDataServices.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/LogOn", ReplyAction="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/LogOnResponse")]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.DataContext> LogOnAsync(BiDataServicesParametersSample.BiDataServices.LogOnRequest logOnRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/LogOnWithToken", ReplyAction="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/LogOnWithTokenRespons" +
            "e")]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.DataContext> LogOnWithTokenAsync(BiDataServicesParametersSample.BiDataServices.LogOnWithTokenRequest logOnRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/LogOff", ReplyAction="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/LogOffResponse")]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.DataContext> LogOffAsync(BiDataServicesParametersSample.BiDataServices.DataContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/ExecuteReport", ReplyAction="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/ExecuteReportResponse" +
            "")]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.ReportResponse> ExecuteReportAsync(BiDataServicesParametersSample.BiDataServices.ReportRequest request, BiDataServicesParametersSample.BiDataServices.DataContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/GetReportList", ReplyAction="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/GetReportListResponse" +
            "")]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.ReportListResponse> GetReportListAsync(BiDataServicesParametersSample.BiDataServices.DataContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/GetReportParameters", ReplyAction="http://www.ultipro.com/dataservices/bidata/2/IBIDataService/GetReportParametersRe" +
            "sponse")]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.ReportParameterResponse> GetReportParametersAsync(string reportPath, BiDataServicesParametersSample.BiDataServices.DataContext context);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingRequest
    {
        
        public PingRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BiDataServicesParametersSample.BiDataServices.PingResponse PingResult;
        
        public PingResponse1()
        {
        }
        
        public PingResponse1(BiDataServicesParametersSample.BiDataServices.PingResponse PingResult)
        {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IBIDataServiceChannel : BiDataServicesParametersSample.BiDataServices.IBIDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BIDataServiceClient : System.ServiceModel.ClientBase<BiDataServicesParametersSample.BiDataServices.IBIDataService>, BiDataServicesParametersSample.BiDataServices.IBIDataService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BIDataServiceClient() : 
                base(BIDataServiceClient.GetDefaultBinding(), BIDataServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IBIDataService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BIDataServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BIDataServiceClient.GetBindingForEndpoint(endpointConfiguration), BIDataServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BIDataServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BIDataServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BIDataServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BIDataServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BIDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.PingResponse1> BiDataServicesParametersSample.BiDataServices.IBIDataService.PingAsync(BiDataServicesParametersSample.BiDataServices.PingRequest request)
        {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.PingResponse1> PingAsync()
        {
            BiDataServicesParametersSample.BiDataServices.PingRequest inValue = new BiDataServicesParametersSample.BiDataServices.PingRequest();
            return ((BiDataServicesParametersSample.BiDataServices.IBIDataService)(this)).PingAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.DataContext> LogOnAsync(BiDataServicesParametersSample.BiDataServices.LogOnRequest logOnRequest)
        {
            return base.Channel.LogOnAsync(logOnRequest);
        }
        
        public System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.DataContext> LogOnWithTokenAsync(BiDataServicesParametersSample.BiDataServices.LogOnWithTokenRequest logOnRequest)
        {
            return base.Channel.LogOnWithTokenAsync(logOnRequest);
        }
        
        public System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.DataContext> LogOffAsync(BiDataServicesParametersSample.BiDataServices.DataContext context)
        {
            return base.Channel.LogOffAsync(context);
        }
        
        public System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.ReportResponse> ExecuteReportAsync(BiDataServicesParametersSample.BiDataServices.ReportRequest request, BiDataServicesParametersSample.BiDataServices.DataContext context)
        {
            return base.Channel.ExecuteReportAsync(request, context);
        }
        
        public System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.ReportListResponse> GetReportListAsync(BiDataServicesParametersSample.BiDataServices.DataContext context)
        {
            return base.Channel.GetReportListAsync(context);
        }
        
        public System.Threading.Tasks.Task<BiDataServicesParametersSample.BiDataServices.ReportParameterResponse> GetReportParametersAsync(string reportPath, BiDataServicesParametersSample.BiDataServices.DataContext context)
        {
            return base.Channel.GetReportParametersAsync(reportPath, context);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IBIDataService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IBIDataService))
            {
                return new System.ServiceModel.EndpointAddress("https://service3.ultipro.ca/services/BIDataService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BIDataServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IBIDataService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BIDataServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IBIDataService);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IBIDataService,
        }
    }
}
